[package]
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = '2018'
name = 'nodle-chain-runtime'
version = '2.0.0'

[features]
default = ['std']
std = [
    'authority-discovery/std',
    'authorship/std',
    'babe/std',
    'balances/std',
    'codec/std',
    'collective/std',
    'frame-executive/std',
    'frame-support/std',
    'grandpa/std',
    'im-online/std',
    'indices/std',
    'membership/std',
    'offences/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'randomness-collective-flip/std',
    'safe-mix/std',
    'serde',
    'session/std',
    'sp-api/std',
    'sp-authority-discovery/std',
    'sp-consensus-babe/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'system/std',
    'system-rpc-runtime-api/std',
    'timestamp/std',
    'transaction-payment/std',
    'utility/std',
    'vesting/std',

    'allocations/std',
    'poa/std',
    'reserve/std',

    'mandate/std',
]

[dependencies.authority-discovery]
default-features = false
package = 'pallet-authority-discovery'
version = '2.0.0-alpha.5'

[dependencies.authorship]
default-features = false
package = 'pallet-authorship'
version = '2.0.0-alpha.5'

[dependencies.babe]
default-features = false
package = 'pallet-babe'
version = '2.0.0-alpha.5'

[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.5'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.collective]
default-features = false
package = 'pallet-collective'
version = '2.0.0-alpha.5'

[dependencies.frame-executive]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.grandpa]
default-features = false
package = 'pallet-grandpa'
version = '2.0.0-alpha.5'

[dependencies.im-online]
default-features = false
package = 'pallet-im-online'
version = '2.0.0-alpha.5'

[dependencies.indices]
default-features = false
package = 'pallet-indices'
version = '2.0.0-alpha.5'

[dependencies.membership]
default-features = false
package = 'pallet-membership'
version = '2.0.0-alpha.5'

[dependencies.offences]
default-features = false
package = 'pallet-offences'
version = '2.0.0-alpha.5'

[dependencies.pallet-transaction-payment-rpc-runtime-api]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.randomness-collective-flip]
default-features = false
package = 'pallet-randomness-collective-flip'
version = '2.0.0-alpha.5'

[dependencies.safe-mix]
default-features = false
version = '1.0.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.session]
default-features = false
features = ['historical']
package = 'pallet-session'
version = '2.0.0-alpha.5'

[dependencies.sp-api]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-authority-discovery]
default-features = false
package = 'sp-authority-discovery'
version = '2.0.0-alpha.5'

[dependencies.sp-consensus-babe]
default-features = false
version = '0.8.0-alpha.5'

[dependencies.sp-block-builder]
default-features = false
version = '2.0.0-alpha.5'
[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-inherents]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-offchain]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-session]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-version]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.system-rpc-runtime-api]
default-features = false
package = 'frame-system-rpc-runtime-api'
version = '2.0.0-alpha.5'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.5'

[dependencies.transaction-payment]
default-features = false
package = 'pallet-transaction-payment'
version = '2.0.0-alpha.5'

[dependencies.utility]
default-features = false
package = 'pallet-utility'
version = '2.0.0-alpha.5'

[dependencies.vesting]
default-features = false
package = 'pallet-vesting'
version = '2.0.0-alpha.5'

[dependencies.allocations]
default-features = false
version = '2.0.0'
package = "pallet-allocations"
path = "../pallets/allocations"

[dependencies.poa]
default-features = false
version = '2.0.0'
package = "pallet-poa"
path = "../pallets/poa"

[dependencies.reserve]
default-features = false
version = '2.0.0'
package = "pallet-reserve"
path = "../pallets/reserve"

[dependencies.mandate]
default-features = false
version = '2.0.0-alpha.5'
package = "pallet-mandate"

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.5'